### ISSUE TITLE
Swimlane/Overlapping bar chart for sessions

### ISSUE THREAD

**Issue by gmazlami** [probr/probr-analysis#26]

**Comment by sebastian-stephan** [comment]
Open issues:
- ~~Clipping does not work (rectangles overlap) After extensive debugging the base tag seems to be the problem: https://github.com/angular/angular.js/issues/8934~~ Fixed [here](https://github.com/probr/probr-analysis/commit/3de83269a23128f0604f6826b303e52111e350c8)
- ~~More fine-grained dynamic axis~~
- ~~Hover over session -> show tags~~
- ~~Very short sessions are not visible when zoomed out~~ #36 proposes min of 30sec sessions
- ~~#35 Display issues with swimlane when data set is big~~ 
- Show names (aliases) instead of mac addresses (if set)
